# Generated by Django 2.1.2 on 2022-01-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0016_auto_20191204_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='jc_number',
            new_name='imei1',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='po_number',
            new_name='imei2',
        ),
        migrations.RemoveField(
            model_name='meltreport',
            name='end_pieces',
        ),
        migrations.RemoveField(
            model_name='meltreport',
            name='scrap_weight',
        ),
        migrations.RemoveField(
            model_name='meltreport',
            name='total_weight',
        ),
        migrations.RemoveField(
            model_name='meltreport',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='work',
            name='amount',
        ),
        migrations.AddField(
            model_name='meltreport',
            name='cgst_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meltreport',
            name='hsc_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='meltreport',
            name='imei1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='meltreport',
            name='imei2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='meltreport',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='meltreport',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='meltreport',
            name='sgst_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meltreport',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meltreport',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
